### PR TITLE
fixes #156 DNT builds broken

### LINKED ISSUE #156: [BUG] - DNT builds not working
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behaviour:

1. run `$ ./_build_npm.ts -v v0.0.0-test -e ./mod.ts -o ./dist`
2. see error 

Image

**Expected behaviour** A clear and concise description of what you expected to
happen.

**Desktop (please complete the following information):**

**Additional context** Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by hardy613**
**Description**

Builds for node didn't output locally - Use JSR with a deno.json and deno.lock file. Use the new shiny standard library for JavaScript via JSR. 

fixes #156 

**Proposed changes in this PR**

- 100% test coverage
- use deno `task` for tasks
- test use the `Deno.test` function for shimmed tests with DNT
- add deno.json
- add deno.lock
- remove test_deps.ts and test_deps_test.ts
- add jsr:@std/assert
- add jsr:@std/cli
- add jsr:@deno/dnt
- remove `const` from type `T` defs in polymorphic 
image
- remove `cmd` from `--allow-run` option

**Things to look at**

- pull the branch and run `$ ../_build_npm.ts -v v0.0.0-test -e ./mod.ts -o ./dist` and observe a complete build

### CODE REVIEW

File: polymorphic.ts [hunk 1]
```diff
@@ -204,7 +204,7 @@ function resolvePolymorphicSwitch(
 /** Uses either the polymorphic resolver or the polymorphic switch resolver to determine the
  * appropriate class, then deserialize the input using Serializable#fromJSON, returning the result
  */
-export function polymorphicClassFromJSON<const T extends Serializable>(
```
Comment (WillForrestMindBridge) [inline polymorphic.ts:207]: to be fair, const in a generic kinda feels funky, not surprised the compiler doesn't like it.

What I am suprised about is it works on github, but not locally with that command.

File: _build_npm.ts [hunk 2]
```diff
@@ -94,5 +94,6 @@ try {
   await Deno.copyFile("README.md", `${flags.o}/README.md`);
   await Deno.copyFile("CHANGELOG.md", `${flags.o}/CHANGELOG.md`);
 } catch (e) {
-  printHelpText(e.message);
+  const { message } = e instanceof Error ? e : { message: `${e}` };
```
Comment (WillForrestMindBridge) [inline _build_npm.ts:99]: 👍

**Review by WillForrestMindBridge — DISMISSED** [review]

File: deno.json [hunk 3]
```diff
@@ -0,0 +1,10 @@
+{
+  "imports": {
+    "@deno/dnt": "jsr:@deno/dnt@^0.42.1",
+    "@std/assert": "jsr:@std/assert@^1.0.13",
+    "@std/cli": "jsr:@std/cli@^1.0.17"
+  },
+  "compilerOptions": {
+    "experimentalDecorators": true
+  }
```
Comment (hardy613) [inline deno.json]: tsconfig.json is not needed now!!

File: deno.json [hunk 4]
```diff
@@ -0,0 +1,10 @@
+{
+  "imports": {
+    "@deno/dnt": "jsr:@deno/dnt@^0.42.1",
+    "@std/assert": "jsr:@std/assert@^1.0.13",
+    "@std/cli": "jsr:@std/cli@^1.0.17"
```
Comment (hardy613) [inline deno.json:5]: jsr is superacool

`@std` is amazing to have. node supports it now too

File: deno.lock
Comment (hardy613) [inline deno.lock:1]: hello darkness my old friend

File: polymorphic.ts (hunk 1 above)
Comment (hardy613) [reply polymorphic.ts:207]: not sure it would work as well as this would enforce[ runtime generic member types ](https://xebia.com/blog/typescript-5-0-and-the-new-const-modifier-on-type-parameters/)

File: serialize_property.ts [hunk 5]
```diff
@@ -54,7 +54,7 @@ interface SerializePropertyArgumentObject {
 export function SerializeProperty(
   args?: string | SerializePropertyArgument,
 ): PropertyDecorator {
-  return function (target: unknown, propertyName: string | symbol): void {
+  return (target: unknown, propertyName: string | symbol): void => {
```
Comment (hardy613) [inline serialize_property.ts:57]: went back to legacy decorators [see our discussion](https://github.com/GameBridgeAI/ts_serialize/discussions/158)

File: tsconfig.json
Comment (hardy613) [inline tsconfig.json:1]: :wave:

File: test_deps_test.ts
Comment (hardy613) [inline test_deps_test.ts:1]: :wave:

File: test_deps.ts
Comment (hardy613) [inline test_deps.ts:1]: :wave:

**Review by hardy613 — COMMENTED** [review]
@PizzaCatKing @ms1111 @WillForrestMindBridge 

I added jsr packages and fixed DNT issues, I would love for this package to also be added to the [JSR](https://jsr.io/) as well. We will also need to update the required tests to be the v2 ones now as [v1 is not supported](https://github.com/GameBridgeAI/ts_serialize/blob/develop/SECURITY.md).

File: deno.json (hunk 3 above)
Comment (WillForrestMindBridge) [reply deno.json]: Do we want experimentalDecorators on again?

What it offers changes release by release.

We could try targeting `ES7` which would be pretty stable and we wouldn't have to worry for a while.

Comment (hardy613) [reply deno.json]: see the discussion https://github.com/GameBridgeAI/ts_serialize/discussions/158

**Comment by WillForrestMindBridge** [comment]
Is there anything that has to be done with the v1 tests on the github side of things?

I see them on the pr, as never running.

**Comment by hardy613** [comment]
@ChrisDufourMB bump plz

**Comment by hardy613** [comment]
> Is there anything that has to be done with the v1 tests on the github side of things?
> 
> I see them on the pr, as never running.

yea, e need to delete them and use the v2 tests as the required, the reason is noted, but v5 of deno.lock is not supported by v1 of deno

File: _build_npm.ts [hunk 6]
```diff
@@ -1,9 +1,9 @@
-#!/usr/bin/env -S deno run --allow-env --allow-read --allow-write --allow-run=npm,cmd --allow-net=deno.land
+#!/usr/bin/env -S deno run --allow-env --allow-read --allow-write --allow-run=npm --allow-net=deno.land,jsr.io
```
Comment (ChrisDufourMB) [inline _build_npm.ts]: We may want to consider being even more strict with `--allow-net`. From what I see the argument allows you to specify specific jsr dependancies:
`--allow-net jsr:@std/http/file-server` (got this from the `deno compile --help` docs).

The current restrictions may allow other unknown dependancies from the same repo to do their evil deeds or whatever, though this may be mitigated by the lockfile.

This isn't mentioned in the deno docs though... further investigation may be required...

File: deno.lock [hunk 7]
```diff
@@ -0,0 +1,25 @@
+{
+  "version": "5",
```
Comment (ChrisDufourMB) [inline deno.lock]: How are we using the lockfile?

From what I understand having a lockfile in deno only prevents changes to the provided modules, as you would expect. We can go further though and make the lockfile frozen, which would prevent modules from updating in place on install, unless explicitly called with `--frozen=false`, which will update the lockfile. This may be preferrable in a CI environemnt. I'm not super familliar with this though, so that's here may be good.

I also tried running `deno install`, which went ahead and updated the lockfile, but also added all the sub-dependances for the dependancies, which weren't there before. Specifically the dependancies for `@deno/dnt` and some others were added.

Can you please explain what you envision the process of updating the dependancies will be if, for example, a new version of `@std/cli` is released and we would like to update to it?

**Review by ChrisDufourMB — COMMENTED** [review]
Thanks for all of this!

Looked though the tests and everything looks good, only have a few comments about the npm build script and the lockfile.

File: _build_npm.ts (hunk 6 above)
Comment (hardy613) [reply _build_npm.ts]: sounds good. 

I'll leave a more detailed comment on these files and changes, but locking down the script to known imports instead of the whole Javascript registry is a good idea :facepalm: I should have thought of that.

File: deno.lock (hunk 7 above)
Comment (hardy613) [reply deno.lock]: > How are we using the lockfile?

Really we shouldn't because we describe ourselves as `zero deps`, however, we use three modules. One from `@deno` and two from `@std`. All imports are only used for testing/CI/CD.

```json
{
  "imports": {
    "@deno/dnt": "jsr:@deno/dnt@^0.42.1",
    "@std/assert": "jsr:@std/assert@^1.0.13",
    "@std/cli": "jsr:@std/cli@^1.0.17"
  }
}
```
- `@deno/dnt` is used within our `_build_npm.ts`, this module transposes deno to node
- `@std/cli` is also used in `_build_npm.ts`, `parseArgs()` for cli options
- `@std/assert` is used for `_test.ts` files

Each module reference was added with `deno add <reference>` we could also use `jsr:@std/assert` directly as an import, but this also creates the lock file.

I saw the `--frozen` option but did not build a snowman with Elsa. If we continue with a lock file we can add that as well!

From the docs we can add to `deno.json`.
```json 
{
    "lock": false
}
```
This would cause deno to skip the integrity checks when downloading the modules on a new machine, but then also allow v1 support. Thinking about the impact, I don't think in production there would be any, only for development. the deno module is zero deps and the npm module is pre-compiled. 

I should have RTFM'd a little more before going wild with the new bells and whistles.

If it makes sense with you to add the `"lock": false` option to `deno.json` I'll just do that and scrub the `deno.lock` from the github cache.

Let me know your thoughts.

**Comment by hardy613** [comment]
@ChrisDufourMB :pray: thanks for the detailed review. Apologies it took an extra day or two to get back to you. The questions you are asking caused me to go back to the docs as well. These features are new-ish with deno and I was learning as I went pulling references from my experience with NPM's lock file management which is why I committed it. 

I left responses, I think we have a way forward, but I'll hold for your thoughts. I like the idea of dropping the lock file all together on this project as production code is zero dependencies. 

Thanks again for taking the time to leave an awesome review.

Cheers :taco: :taco: :taco: :clock630:

File: _build_npm.ts (hunk 6 above)
Comment (hardy613) [reply _build_npm.ts]: I tried this and it did not work. 

image


further reading of the docs, `jsr.io` is enabled by default. seems like [a trusted list exists](https://docs.deno.com/runtime/fundamentals/security/): 

    https://deno.land/
    https://jsr.io/
    https://esm.sh/
    https://raw.githubusercontent.com
    https://gist.githubusercontent.com

File: .github/workflows/ts_serialize_tests.yml [hunk 8]
```diff
@@ -30,17 +30,23 @@ jobs:
...
+        run: deno task test:coverage
+
+      - name: Generate coverage report
+        run: deno task test:coverage:report
+
+      - name: Coverage report
+        uses: VeryGoodOpenSource/very_good_coverage@v2
+        with:
+          path: "./coverage/lcov.info"
+          min_coverage: 100
```
Comment (hardy613) [inline .github/workflows/ts_serialize_tests.yml:71]: :100:

File: .github/workflows/ts_serialize_tests.yml [hunk 9]
```diff
@@ -30,17 +30,23 @@ jobs:
...
-        run: deno fmt --check -c tsconfig.json
+        run: deno task fmt --check
         if: matrix.os != 'windows-latest'
 
-      - name: Cache dependencies
-        run: deno cache test_deps.ts
-
       - name: Deno test
-        run: deno test --doc -c tsconfig.json
+        run: deno task test:coverage
```
Comment (hardy613) [inline .github/workflows/ts_serialize_tests.yml:62]: `task` uses deno.json auto discovery

File: strategy/utils.ts [hunk 10]
```diff
@@ -7,10 +7,15 @@ export type NewSerializable<T> = T & (new () => Serializable);
...
-  } else if (isFunctionSerializable(type)) {
-    return type();
+  } else if (!isNewableType && isFunctionSerializable(type)) {
+    const instance = type();
+    if (instance instanceof Serializable) {
+      return instance;
+    }
   }
+
   throw new Error(ERROR_GET_NEW_SERIALIZABLE_SERIALIZABLE_NOT_RETURNED);
```
Comment (hardy613) [inline strategy/utils.ts:20]: actually fixed a bug where the error was never reached, thanks test coverage!

File: strategy/utils_test.ts [hunk 11]
```diff
@@ -39,3 +39,23 @@ test({
...
+      fail("Expected getNewSerializable error to be thrown");
+    } catch (e) {
+      assert(e instanceof Error);
+      assertEquals(
+        e.message,
+        ERROR_GET_NEW_SERIALIZABLE_SERIALIZABLE_NOT_RETURNED,
+      );
+    }
+  },
+});
```
Comment (hardy613) [inline strategy/utils_test.ts:61]: 100% coverage

**Review by hardy613 — COMMENTED** [review]
@ChrisDufourMB i went ahead and made the changes

**Comment by hardy613** [comment]
Okie doke, I think I got it all now, v1 tests, v2 tests++, hopefully when v3 is out it won't affect ci as much.

File: strategy/to_json/from_serializable.ts [hunk 12]
```diff
@@ -5,12 +5,10 @@ import { ToJSONStrategy } from "../compose_strategy.ts";
...
 /** serialize data using `tsSerialize` on a subclass Serializable type */
 export function fromSerializable(): ToJSONStrategy {
-  return (value: Serializable | Serializable[]): JSONValue => {
+  return (value: Serializable[] | null): JSONValue => {
     if (Array.isArray(value)) {
       return value.map((item) => item.tsSerialize());
     }
-    // Objects can be null, return them without further serialization.
-    // Double cast required to return a JSONValue
-    return value ? value.tsSerialize() : value as null as JSONValue;
```
Comment (hardy613) [inline strategy/to_json/from_serializable.ts:14]: turns out this is never reached as `toPojo(serializable)` will be recursive on `Serializable`'s

File: SECURITY.md [hunk 13]
```diff
@@ -4,11 +4,20 @@ Below is a table of supported versions.
...
 | ------- | ------------------ |
 | 2.x     | :white_check_mark: |
 | 1.x     | :x:                |
 
+### Deno
+
+| Version | Supported          |
+| ------- | ------------------ |
+| 2.x     | :white_check_mark: |
+| 1.x     | :white_check_mark: |
```
Comment (hardy613) [inline SECURITY.md:19]: feels good

File: _build_npm.ts [hunk 14]
```diff
@@ -48,13 +47,16 @@ if (flags.h) {
...
+
 try {
   await emptyDir(flags.o);
 
   await build({
+    importMap: "./deno.json",
     entryPoints: [flags.e],
     outDir: flags.o,
-    compilerOptions: { target: "ES2021" },
+    compilerOptions: { lib: ["ESNext"], experimentalDecorators: true },
```
Comment (WillForrestMindBridge) [inline _build_npm.ts:59]: I always get a little unnerved when the target is unnumbered like "ESNext".

When does ESNext stop 😂?

File: strategy/to_json/from_serializable.ts (hunk 12 above)
Comment (WillForrestMindBridge) [reply strategy/to_json/from_serializable.ts:14]: ⚠️ 

Is an array of nulls possible now? Should we write a test to check that case?

Eg.

```
value = [null,null,null,null]
```

I suppose that was always possible, just noticing now that you've cleaned up a bit.

File: _build_npm.ts (hunk 14 above)
Comment (hardy613) [reply _build_npm.ts:59]: image


yea without it the npm build fail missing types on Sets and ErrorOptions

File: strategy/to_json/from_serializable.ts (hunk 12 above)
Comment (hardy613) [reply strategy/to_json/from_serializable.ts:14]: :100: nice catch, adding the test found a bug, it's fixed now and we will support this request next release, thanks @WillForrestMindBridge

File: strategy/to_json/from_serializable_test.ts [hunk 15]
```diff
@@ -122,3 +122,28 @@ test({
     );
   },
 });
+
+Deno.test({
```
Comment (WillForrestMindBridge) [inline strategy/to_json/from_serializable_test.ts:126]: Nice 👍

**Review by WillForrestMindBridge — APPROVED** [review]
The othes may be a while before they get to review. They are extremely busy until end of month.

I look forward to trying out tsSerialize v2 in a bigger project.

**Comment by hardy613** [comment]
@ChrisDufourMB bump please.

**Review by ChrisDufourMB — APPROVED** [review]
