### PR TITLE
fixes #151

### LINKED ISSUE #151: [BUG] - Nested objects cannot be serialized if they are set to null
**Describe the bug** Any nested object that is also a class cannot be serialized if it is set to null.
When set to undefined, it can serialize properly, but not with null.

Image

**To Reproduce** Steps to reproduce the behaviour:

1. Create an class (A) with another class (B) as a field
2. Create the class
3. Set the field to null
4. Attempt to use .tsSerialize() or JSON.stringify or toJSON()
5. See error

**Expected behaviour** The primitive "null" is chosen as the serialization value.

**Desktop (please complete the following information):**

- OS: MacOS, linux
- Browser: FIrefox + chrome
- Version 2.0.3

### PR DESCRIPTION
**Pull request by WillForrestMindBridge**
**Description**

### Issues fixed ###
See issue #151 

**Proposed changes in this PR**

Issue 151
- Allow the fromSerializable strategy to return the primitive null value instead of having a null pointer exception.
  - We expect to send null in the request.
- Undefined is protected at the level above, which makes sense, as we don't want to send it over the wire. No changes to be made in that case.

**Things to look at**

- [x] Test coverage
- [x] Code Style
- [x] Documentation (`README.md`, `CHANGELOG.md`, etc..)

### CODE REVIEW

**Comment by WillForrestMindBridge** [comment]
@hardy613  I was going to push this branch onto your remote fork, but github didn't let me. Nothing can ever be simple right?

I've added the 151 fix onto your changes.

**Comment by hardy613** [comment]
That makes sense, the order will be to merge mine, then this should clean up to only what is needed to fix #151 and we can merge it, then @ChrisDufourMB can release

**Comment by hardy925** [comment]
Did you add yourself to the contributors.md file? You should. Reporting and fixing a bug is great work. Thanks again Will.

**Comment by hardy613** [comment]
This PR is a child of #153 the bulk of the specific change Will is making is in the commit [08f2aa2e](https://github.com/GameBridgeAI/ts_serialize/pull/155/commits/08f2aa2eeed11a0c5483d948f3d1d35a93c34de6)

File: strategy/to_json/from_serializable.ts [hunk 1]
```diff
@@ -8,6 +8,10 @@ export function fromSerializable(): ToJSONStrategy {
   return (value: Serializable | Serializable[]): JSONValue => {
     if (Array.isArray(value)) {
       return value.map((item) => item.tsSerialize());
+    } else if (value === null) {
+      // Objects can be null, return them without further serialization.
+      // Double cast required to return a JSONValue
+      return value as null as JSONValue;
     }
     return value.tsSerialize();
```
Comment (hardy613) [inline strategy/to_json/from_serializable.ts]: Hmm, I don't think we need the `else if`, it could be another `if`, this is because the above `if` `return`'s and exits anyways so an `else` is not needed. I am also thinking about something like `return value ? value.tsSerialize() : value;`

what are your thoughts? Nice comments to btw!

File: strategy/to_json/from_serializable_test.ts [hunk 2]
```diff
@@ -43,6 +43,33 @@ test({
   },
 });
 
+test({
+  name:
+    "fromSerializable - arrays of nested objects with an object set to null",
+  fn() {
+    class Test1 extends Serializable {
+      @SerializeProperty("nested_property")
+      serializeMe = 999;
```
Comment (hardy613) [inline strategy/to_json/from_serializable_test.ts]: NIT: if we happen to go back for code changes in the PR could we add `public ` to these members, only for consistency, again it's not a blocker.

File: .github/CONTRIBUTORS.md [hunk 3]
```diff
@@ -7,3 +7,4 @@
 - [@rgrosset](https://github.com/rgrosset) :shipit:
 - [@ms1111](https://github.com/ms1111) :eyes:
 - [@khan-saim](https://github.com/khan-saim)
+- [@WillForrestMindBridge](https://github.com/WillForrestMindBridge)
```
Comment (hardy613) [inline .github/CONTRIBUTORS.md:10]: :fire:

**Review by hardy613 — COMMENTED** [review]
:+1: 

should fix #151, thanks!

File: strategy/to_json/from_serializable_test.ts (hunk 2 above)
Comment (WillForrestMindBridge) [reply strategy/to_json/from_serializable_test.ts]: I have it open still, 1 second...

File: strategy/to_json/from_serializable.ts (hunk 1 above)
Comment (WillForrestMindBridge) [reply strategy/to_json/from_serializable.ts]: Sure

**Comment by WillForrestMindBridge** [comment]
Squashed the PR changes, so fix 151 is still a single commit.

File: strategy/to_json/from_serializable.ts (hunk 1 above)
Comment (WillForrestMindBridge) [reply strategy/to_json/from_serializable.ts]: 😅 

I changed to

```
    return value ? value.tsSerialize() : value as null as JSONValue;
```

File: strategy/to_json/from_serializable.ts [hunk 4]
```diff
@@ -9,6 +9,8 @@ export function fromSerializable(): ToJSONStrategy {
     if (Array.isArray(value)) {
       return value.map((item) => item.tsSerialize());
     }
-    return value.tsSerialize();
+    // Objects can be null, return them without further serialization.
+    // Double cast required to return a JSONValue
+    return value ? value.tsSerialize() : value as null as JSONValue;
```
Comment (hardy613) [inline strategy/to_json/from_serializable.ts:14]: this works too, the comments are what really helps us here, so thanks again for those.

**Review by hardy613 — DISMISSED** [review]
LGTM - let's get #153 in first though

**Review by hardy613 — APPROVED** [review]
Thanks @WillForrestMindBridge !
