### PR TITLE
Fix empty class serialization

### LINKED ISSUE #83: [BUG] - Unable to serialize/de-serialize classes without any serializable properties
**Describe the bug**

**To Reproduce**
- Create the following class:
```ts
class TestSerializable extends Serializable {}
```
- Try to serialize it/deserialize an json object into it
- Serialization will fail with the following error:
`Unable to load serializer properties for the given context: [object Object]`

**Expected behaviour**
The class should serialize to `{}` and inherit values from it's parents

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser: `deno`
- Version: 1.5.4

**Additional context**

### PR DESCRIPTION
**Pull request by ChrisDufourMB**
## Fixes

fixes #83 

## Description

Fixes issue where classes without any `@SerializeProperty()` decorator fails to be serialized

## Proposed changes in this PR

- Add logic to create serialization definitions on class construction if they weren't created when a `SerializeProperty` decorator was processed. This is recursive as parent constructors aren't called unless explicitly called via `super()`

## Things to look at

- [x] Test coverage
- [x] Code Style
- [x] Documentation (READMEs etc)

### CODE REVIEW

**Review by ms1111 — APPROVED** [review]
Looks sane

File: serializable.ts [hunk 1]
```diff
@@ -45,6 +45,52 @@ export abstract class Serializable {
...
+      SERIALIZABLE_CLASS_MAP.set(
+        targetPrototype,
+        new SerializePropertyOptionsMap(parentMap),
+      );
+      const newSerializableOptions = SERIALIZABLE_CLASS_MAP.get(
+        targetPrototype,
+      );
+
+      if (!newSerializableOptions) {
+        // This shouldn't happen considering we just added that value
```
Comment (hardy925) [inline serializable.ts:85]: I am honoured we found a way to have a legit `This shouldn't happen` comment!!!!

:))))))))

**Review by hardy925 — APPROVED** [review]
🔥 🧯
